.TH EDASH-CLI "1" "June 2016" "edash-cli 0.12"
.SH NAME
edash-cli \- a remote procedure call client for EDash Core.
.SH SYNOPSIS
edash-cli [options] <command> [params] \- Send command to EDash Core.
.TP
edash-cli [options] help \- Asks EDash Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the edash-cli program. edash-cli is an RPC client used to send commands to EDash Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBedashd\fP, \fBedash.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
